openapi: 3.0.0
info:
  title: API BS Product Statement V2
  description: Permite obtener el estado de cuenta del cliente en formato pdf para cuenta de tipo ahorros, corriente, maestra, CTS, Créditos ALS, Mercado Capitales y de tarjeta de crédito.
  version: "2.0.0"
servers: 
  - url: /customer-management/product-service/v2
x-bcp-api-type: BS
x-bcp-api-id: product-statement
externalDocs:
  description: Para más información de la API BS Product Statement V2
  url: https://confluence.lima.bcp.com.pe/display/APCSPUB/Business+Product+Statement+V2
paths:
  /product-statements/retrieve:
    post:
      tags:
        - Product Statement
      summary: >-
        Permite obtener el estado de cuenta de tipo ahorros, corriente, maestra, CTS, Créditos ALS, Mercado Capitales y de tarjeta de crédito para un cliente (natural o juridica). El pdf devuelto podrá ser generado con clave o no.
      description: >+
        ### Acerca de la funcionalidad expuesta

        El servicio permite la consulta de un estado de cuenta de tipo Ahorros, Corriente, Maestra y de Tarjeta de Crédito.
        
        Cuando se realiza la consulta, mediante el ingreso de información como id de cuenta, mes y año se devolverá la información del estado de cuenta con un formato de Base64.
        
        En caso de enviar el keyValue como parámetro se devolverá la
        información del estado de cuenta con un formato de Base64 cifrado.
        
        ### Información complementaria  
        

        ### Precondiciones para el consumo de esta versión de la API

        No aplica.
        
        ### Data de Prueba.
        
        Considerar la información del json.
        
        ### Query Parameters válidos en esta versión de la API
        
        No Aplica.

        ### Usos válidos de Query Parameters

        No Aplica.
        
        ### Variantes válidas del Payload (Cuerpo del mensaje)
        
            ### Caso 01: Obtener estado de cuenta con número de cuenta, PDF sin contraseña:
          ```json
        
              {
                "product": {
                  "productId" : "19111140480009",
                  "productDetail" : {
                    "family" : {
                      "code" : "005" 
                    }
                  }
                },
                "documentDate" : {
                  "year" : "2017",
                  "month" : "08"
                }
              }
        
           ```
              
            ### Caso 02: Obtener estado de cuenta con número de cuenta, PDF con contraseña:
    
          ```json
        
              {
                "product": {
                  "productId" : "19111140480009",
                  "productDetail" : {
                    "family" : {
                      "code" : "005"
                    }
                  }
                },
                "documentDate" : {
                  "year" : "2017",
                  "month" : "08"
                },
                "keyValue" : "04586598"
              }
        
           ```
           
            ### Caso 03: Obtener estado de cuenta de producto de mercado capitales, PDF con contraseña:
    
          ```json
        
              {
                "product": {
                  "productId" : "000000143687927",
                  "productDetail" : {
                    "family" : {
                      "code" : "050"
                    },
                    "tioaux" : {
                      "code" : "CTEORD"
                    }
                  },
                  "employeeAccountType" : {
                      "code" : "1"
                    }
                },
                "documentDate" : {
                  "year" : "2017",
                  "month" : "08",
                  "day" : "10"
                },
                "keyValue" : "04586598"
              }
        
           ```

            ### Caso 04: Obtener estado de cuenta de producto de mercado capitales, PDF sin contraseña:
    
          ```json
        
              {
                "product": {
                  "productId" : "000000143687927",
                  "productDetail" : {
                    "family" : {
                      "code" : "050"
                    },
                    "tioaux" : {
                      "code" : "CTEORD"
                    }                    
                  },
                  "employeeAccountType" : {
                      "code" : "1"
                  }
                },
                "documentDate" : {
                  "year" : "2017",
                  "month" : "08",
                  "day" : "10"
                }
              }
        
           ```           
       

        ### Lista de Valores usadas en esta versión de la API
        
        <br/>
        
        | Atributo | Valor |
        
        |----------|----------|
        
        |    product.productDetail.family.code | Valores:  003 = Tarjetas de Crédito, 004 = Cuenta Corriente, 005 = Cuentas de Ahorro, 007 = Cuenta Maestra, 009 = CTS, 020 = Créditos ALS (vehiculares, hipotecarios, efectivos), 050 = Mercado de Capitales (FondoMutuo y Polizas)|
        
        | product.employeeAccountType.code | Valores: 0, 1, 3, 5 |                            


        ### Códigos de error usados en esta versión de la API

        | Código | HTTP Status | Descripción |

        |--------|-------------|--------|

        | TL0003 | 400 |Los datos proporcionados no son validos. |
        
        | TL0006 | 409 | Los datos proporcionados no cumplen con los criterios para ser procesado |

        | TL0004 | 500 |El servicio no se encuentra disponible. Por favor reintente
        mas tarde. |

        | TL0005 | 500 | No se encontro el servidor solicitado. |

        | TL0007 | 500 |Ocurrio un error en el servicio externo. |

        | TL0009 | 500 | Ocurrio un error intentando invocar servicios externos. Por
        favor contactarse con el Soporte Tecnico. |

        | TL0011 | 401 | No esta autorizado correctamente para ejecutar esta operacion. |

        | TL9999 | 500 |Ocurrio un error inesperado. Por favor contactarse con el
        Soporte Tecnico. |

      operationId: retrieveProductStatement
      x-atlas-header:
        $ref: '#/components/schemas/ProductStatementsHeaders'
      parameters:
        - $ref: 'https://swaggerhub.lima.bcp.com.pe/v1/domains/BCP_Org/Api-Header-Domain/1.0.0#/components/parameters/Authorization'
        - $ref: 'https://swaggerhub.lima.bcp.com.pe/v1/domains/BCP_Org/Api-Header-Domain/1.0.0#/components/parameters/Request-ID'
        - $ref: 'https://swaggerhub.lima.bcp.com.pe/v1/domains/BCP_Org/Api-Header-Domain/1.0.0#/components/parameters/request-date'
        - $ref: 'https://swaggerhub.lima.bcp.com.pe/v1/domains/BCP_Org/Api-Header-Domain/1.0.0#/components/parameters/app-code' 
        - $ref: 'https://swaggerhub.lima.bcp.com.pe/v1/domains/BCP_Org/Api-Header-Domain/1.0.0#/components/parameters/caller-name'  
        - $ref: 'https://swaggerhub.lima.bcp.com.pe/v1/domains/BCP_Org/Api-Header-Domain/1.0.0#/components/parameters/Ocp-Apim-Subscription-Key'
      responses:
        '200':
          description: Se obtiene el estado de cuenta de un cliente.
          content:
            application/stream+json:
              schema:
                $ref: '#/components/schemas/ProductStatementsResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/ProductStatementsResponse'
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/ProductStatementsResponse'
        "204":
          description: No se encontro estado de cuenta.
        '400':
          description: El cliente envió datos incorrectos.
          content:
            application/stream+json:
              schema:
                $ref: 'https://swaggerhub.lima.bcp.com.pe/v1/domains/BCP_Org/Api-Header-Domain/1.0.0#/components/schemas/ApiException'
            application/json:
              schema:
                $ref: 'https://swaggerhub.lima.bcp.com.pe/v1/domains/BCP_Org/Api-Header-Domain/1.0.0#/components/schemas/ApiException'
            application/json;charset=UTF-8:
              schema:
                $ref: 'https://swaggerhub.lima.bcp.com.pe/v1/domains/BCP_Org/Api-Header-Domain/1.0.0#/components/schemas/ApiException'
        '409':
          description: Error funcional, se debe enviar más datos.
          content:
            application/stream+json:
              schema:
                $ref: 'https://swaggerhub.lima.bcp.com.pe/v1/domains/BCP_Org/Api-Header-Domain/1.0.0#/components/schemas/ApiException'
            application/json:
              schema:
                $ref: 'https://swaggerhub.lima.bcp.com.pe/v1/domains/BCP_Org/Api-Header-Domain/1.0.0#/components/schemas/ApiException'
            application/json;charset=UTF-8:
              schema:
                $ref: 'https://swaggerhub.lima.bcp.com.pe/v1/domains/BCP_Org/Api-Header-Domain/1.0.0#/components/schemas/ApiException'                
        '500':
          description: Error al ejecutar proceso.
          content:
            application/stream+json:
              schema:
                $ref: 'https://swaggerhub.lima.bcp.com.pe/v1/domains/BCP_Org/Api-Header-Domain/1.0.0#/components/schemas/ApiException'
            application/json:
              schema:
                $ref: 'https://swaggerhub.lima.bcp.com.pe/v1/domains/BCP_Org/Api-Header-Domain/1.0.0#/components/schemas/ApiException'
            application/json;charset=UTF-8:
              schema:
                $ref: 'https://swaggerhub.lima.bcp.com.pe/v1/domains/BCP_Org/Api-Header-Domain/1.0.0#/components/schemas/ApiException'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductStatementsRequest'
          application/json;charset=UTF-8:
            schema:
              $ref: '#/components/schemas/ProductStatementsRequest'
        description: Entrada del Servicio
        required: true
components:
  schemas:
    ProductStatementsHeaders:
      type: object
    ProductStatementsRequest:
      type: object
      required:
        - product
        - documentDate
      properties:
        product:
          $ref: 'https://swaggerhub.lima.bcp.com.pe/v1/domains/BCP_Org/domain-product-statement-v2/2.0.0#/components/schemas/Product'
        documentDate:
          $ref: 'https://swaggerhub.lima.bcp.com.pe/v1/domains/BCP_Org/domain-product-statement-v2/2.0.0#/components/schemas/DocumentDate'    
        keyValue:
          type: string
          example: 09876756
          description: N?mero de documento para encriptar el pdf
          minLength: 1
          maxLength: 30
          pattern: '^[A-Za-z0-9]*$'
      title: ProductStatementsRequest
    ProductStatementsResponse:
      type: object
      properties:
        extension:
          $ref: 'https://swaggerhub.lima.bcp.com.pe/v1/domains/BCP_Org/domain-product-statement-v2/2.0.0#/components/schemas/Extension'
        size:
          $ref: 'https://swaggerhub.lima.bcp.com.pe/v1/domains/BCP_Org/domain-product-statement-v2/2.0.0#/components/schemas/AccountStatementSize'
        data:
          type: string
          format: byte
          example: liNmNiNmYzZjA2YmE4OGQ
          description: Contenido del archivo
      title: ProductStatementsResponse